##
## Script Name: modelBuild.yaml
## Description: Config file for feature extraction and model build
##

# Model Parameters
model_name: 'xception'
target_size: (299,299)
input_shape: (299,299,3)
unfreeze_layer_idx: 126

# model_name_effnet: 'efficient net'
# target_size_effnet: (456,456)
# input_shape_effnet: (456,456,3)
# unfreeze_layer_idx_effnet: 555

unfreeze_layers: 'N'
train_batch_size: 32
valid_batch_size: 32
test_batch_size: 1
learning_rate: 0.001
model_save_filepath: "./multi_label_model_{epoch:02d}.h5"
early_stopping_patience: 3
epochs: 50
final_model_save_path: "./models/xception_model.h5"
dataset_shuffle: 'Y'
training: 'Y'
multi_label_prediction_results: "results.csv"
extract_embeddings: 'Y'
feature_list: './features/xception_features.pickle'
filename_list: './features/xception_filenames.pickle'
feature_filename_dict: "./features/xception_feature_filename_dict.pickle"
problem_images: ['39403.jpg', '39410.jpg', '39401.jpg', '39425.jpg', '12347.jpg']

# dataset_nm: "styles.csv"
dataset_nm: 'fashion-dataset-resized-noface-299.csv'
input_path: '/kaggle/input/fashion-dataset-resized/'
imgs_path: '/kaggle/input/fashion-dataset-resized/fashion-dataset-resized-noface-256/fashion-dataset-resized-noface-256/images/'

# Index path
index_path: './index/xception_faiss_index.index'
annoy_index_path: './index/xception_annoy_index.index'
